name: npm-publish
on:
  push:
    branches:
      - main 
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: use-format-amount-input
      uses: actions/checkout@v2
    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.9
      with:
        commit_pattern: "^Release (\\S+)"
        workspace: "./use-format-amount-input"
        publish_command: "npm publish"
        publish_args: "--non-interactive"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
